export interface Trademark {
  id: string
  logo: string
  logoColor: string
  name: string
  isExpiring: boolean
  category: string
  registrationDate: string
  applicant: string
  isBookmarked: boolean
}

export const trademarks: Trademark[] = [
  {
    id: "1",
    logo: "T",
    logoColor: "bg-blue-500",
    name: "테크노베이션",
    isExpiring: true,
    category: "기업 로고",
    registrationDate: "2023-05-15",
    applicant: "홍길동",
    isBookmarked: true,
  },
  {
    id: "2",
    logo: "🌿",
    logoColor: "bg-white",
    name: "그린에코",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-08-22",
    applicant: "김철수",
    isBookmarked: false,
  },
  {
    id: "3",
    logo: "🏠",
    logoColor: "bg-white",
    name: "스마트홈",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2024-01-10",
    applicant: "이영희",
    isBookmarked: true,
  },
  {
    id: "4",
    logo: "H+",
    logoColor: "bg-pink-100",
    name: "헬스케어플러스",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2023-11-05",
    applicant: "박민수",
    isBookmarked: false,
  },
  {
    id: "5",
    logo: "📚",
    logoColor: "bg-white",
    name: "에듀테크",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-09-18",
    applicant: "최수진",
    isBookmarked: false,
  },
  {
    id: "6",
    logo: "🥕",
    logoColor: "bg-white",
    name: "푸드마켓",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2024-02-14",
    applicant: "홍길동",
    isBookmarked: true,
  },
  {
    id: "7",
    logo: "F",
    logoColor: "bg-purple-600 text-white",
    name: "패션스타일",
    isExpiring: true,
    category: "기업 로고",
    registrationDate: "2023-07-30",
    applicant: "김철수",
    isBookmarked: false,
  },
  {
    id: "8",
    logo: "🚗",
    logoColor: "bg-white",
    name: "모빌리티",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-12-20",
    applicant: "이영희",
    isBookmarked: true,
  },
  {
    id: "9",
    logo: "B",
    logoColor: "bg-red-100",
    name: "뷰티케어",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2024-03-05",
    applicant: "박민수",
    isBookmarked: false,
  },
  {
    id: "10",
    logo: "💰",
    logoColor: "bg-white",
    name: "핀테크솔루션",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2023-10-12",
    applicant: "최수진",
    isBookmarked: true,
  },
  {
    id: "11",
    logo: "A",
    logoColor: "bg-green-500 text-white",
    name: "아그리텍",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-06-08",
    applicant: "정대현",
    isBookmarked: false,
  },
  {
    id: "12",
    logo: "🎮",
    logoColor: "bg-white",
    name: "게임월드",
    isExpiring: true,
    category: "기업 로고",
    registrationDate: "2023-04-25",
    applicant: "홍길동",
    isBookmarked: true,
  },
  {
    id: "13",
    logo: "S",
    logoColor: "bg-orange-400 text-white",
    name: "스포츠라이프",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2024-01-28",
    applicant: "김철수",
    isBookmarked: false,
  },
  {
    id: "14",
    logo: "🎵",
    logoColor: "bg-white",
    name: "뮤직플레이",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-09-03",
    applicant: "이영희",
    isBookmarked: true,
  },
  {
    id: "15",
    logo: "C",
    logoColor: "bg-cyan-500 text-white",
    name: "클라우드넷",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2023-11-22",
    applicant: "박민수",
    isBookmarked: false,
  },
  {
    id: "16",
    logo: "🏥",
    logoColor: "bg-white",
    name: "메디컬플러스",
    isExpiring: true,
    category: "서비스 상표",
    registrationDate: "2023-03-17",
    applicant: "최수진",
    isBookmarked: true,
  },
  {
    id: "17",
    logo: "D",
    logoColor: "bg-indigo-500 text-white",
    name: "데이터랩",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2024-02-09",
    applicant: "정대현",
    isBookmarked: false,
  },
  {
    id: "18",
    logo: "🌍",
    logoColor: "bg-white",
    name: "글로벌트레이드",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2023-08-14",
    applicant: "홍길동",
    isBookmarked: false,
  },
  {
    id: "19",
    logo: "E",
    logoColor: "bg-amber-500 text-white",
    name: "에너지솔루션",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-12-05",
    applicant: "김철수",
    isBookmarked: true,
  },
  {
    id: "20",
    logo: "📱",
    logoColor: "bg-white",
    name: "앱스토어코리아",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2024-03-20",
    applicant: "이영희",
    isBookmarked: false,
  },
  {
    id: "21",
    logo: "L",
    logoColor: "bg-rose-500 text-white",
    name: "럭셔리브랜드",
    isExpiring: true,
    category: "상표 등록",
    registrationDate: "2023-05-30",
    applicant: "박민수",
    isBookmarked: true,
  },
  {
    id: "22",
    logo: "🍳",
    logoColor: "bg-white",
    name: "쿠킹스튜디오",
    isExpiring: false,
    category: "서비스 상표",
    registrationDate: "2023-10-08",
    applicant: "최수진",
    isBookmarked: false,
  },
  {
    id: "23",
    logo: "P",
    logoColor: "bg-teal-500 text-white",
    name: "펫케어",
    isExpiring: false,
    category: "기업 로고",
    registrationDate: "2024-01-15",
    applicant: "정대현",
    isBookmarked: true,
  },
  {
    id: "24",
    logo: "🎨",
    logoColor: "bg-white",
    name: "아트갤러리",
    isExpiring: false,
    category: "상표 등록",
    registrationDate: "2023-07-12",
    applicant: "홍길동",
    isBookmarked: false,
  },
  {
    id: "25",
    logo: "N",
    logoColor: "bg-slate-700 text-white",
    name: "뉴스포털",
    isExpiring: true,
    category: "서비스 상표",
    registrationDate: "2023-02-28",
    applicant: "김철수",
    isBookmarked: true,
  },
]

export const categories = ["전체 카테고리", "기업 로고", "서비스 상표", "상표 등록"]
export const statuses = ["전체 상태", "등록", "소멸 예정", "출원 중"]
